### ISSUE TITLE
Current version is marked as yanked in pypi and only version available for py 3.11

### ISSUE THREAD

**Issue by hajapy** [conda-forge/cryptography-feedstock#108]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#3802---2022-10-11-yanked
https://pypi.org/project/cryptography/38.0.2/

The 38.0.2 release has been yanked due to:
> ... a regression in OpenSSL.

I think it might be a good idea to update main here to 38.0.1 so it can rebuild for python 3.11 and possibly consider marking the 38.0.2 packages as broken. This might interfere with the ongoing py311 migration. 

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by h-vetinari** [comment]
Thanks for the report.

This is not an issue for us in conda-forge, because we do not bundle openssl with cryptography. Since we never shipped openssl 3.0.6, there's no way to be affected by this in conda-forge. Also, it's "only" a performance regression, not something security critical.

**Comment by hajapy** [comment]
Thanks for the clarification @h-vetinari. "Yanked" is fairly rare on pypi so when I saw that associated with cryptography I thought it could be a significant issue.

**Comment by h-vetinari** [comment]
> Thanks for the clarification @h-vetinari. "Yanked" is fairly rare on pypi so when I saw that associated with cryptography I thought it could be a significant issue.

They were following suit with [OpenSSL](https://mta.openssl.org/pipermail/openssl-announce/2022-October/000237.html). The whole thing seemed overblown, but what do I know... 🤷
