### ISSUE TITLE
Upload of cryptography 41.0.3 package failed

### ISSUE THREAD

**Issue by tkilias** [conda-forge/cryptography-feedstock#122]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I checked the list of available versions on https://anaconda.org/conda-forge/cryptography and it seems that the version 41.0.3 is missing. I also saw that the CI for commit https://github.com/conda-forge/cryptography-feedstock/commit/b674d8c1c87bcc722aa77d9e0fa359242ff584c0 failed with a timeout during the upload.

### Installed packages

```shell
Doesn't apply.
```

### Environment info

```shell
Doesn't apply.
```

**Comment by h-vetinari** [comment]
Thanks for pointing this out! I've retriggered the builds and everything is back to green and published now
