### ISSUE TITLE
"ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory" in Python 3.6

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/cryptography-feedstock#15]
I'm getting this error in Travis CI, for Python 3.6 only (3.5 works fine):

```
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module>
    from cryptography.hazmat.bindings._padding import lib
ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
```

See https://travis-ci.org/drdoctr/doctr/jobs/439773106#L2272-L2273

**Comment by gireek** [comment]
sudo apt-get install libpython3.6. Try this once

**Comment by ocefpaf** [comment]
I believe this was fixed a while back. Closing this.

**Comment by ajinkya933** [comment]
$ sudo apt-get install libpython3.6Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libpython3.6
E: Couldn't find any package by glob 'libpython3.6'
E: Couldn't find any package by regex 'libpython3.6'
