### ISSUE TITLE
one build includes a core python pyc

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/cryptography-feedstock#35]
For some reason, the build `linux-64/cryptography-2.8-py38h72c5cf5_0.tar.bz2` includes the file 
```
lib/python3.8/__pycache__/_sysconfigdata_x86_64_conda_cos6_linux_gnu.cpython-38.pyc
```
which it definitely should not; this file is in the `python` package, and the conflict can occasionally cause `conda` to complain (or sometimes for it to just silently override one with the other).

This doesn't seem to be the case for other platforms / python versions that I've checked, and when I run `build-locally.py` it's not included. So this is probably just some fluke in conda-build that has nothing to do with this package in particular.

I'm going to just bump the build number so that a new version comes out, which hopefully doesn't do this. :)

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by dougalsutherland** [comment]
Looks like the new builds fixed it. Some weird race condition I guess.
