### ISSUE TITLE
Keep building python 3.6 for a while longer on this feedstock?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/cryptography-feedstock#73]
The next rerender is going to remove python 3.6 (following https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/1947 & https://github.com/conda-forge/conda-forge.github.io/pull/1516). 

I wanted to discuss if for security-relevant packages, python 3.6 should still be supported a while longer? Given that there are only a handful of affected feedstocks, I think this would be manageable.

**Comment by ocefpaf** [comment]
> I wanted to discuss if for security-relevant packages, python 3.6 should still be supported a while longer? Given that there are only a handful of affected feedstocks, I think this would be manageable.

Manageable from a CI perspective? Yes. From a human in the loop? Probably not. However, we can probably create a list of these packages and add a "special security bot migration/build" for them.

**Comment by jaimergp** [comment]
Python 3.6 variants have not been built for a while, so we can close here :)
